title: Neurodiversity Blog
description: Research-backed insights for the neurodivergent community
baseurl: ""
url: "https://neurodiversityblog.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: Your Name
twitter:
  username: yourtwitterhandle
  card: summary

# Navigation
header_pages:
  - about.md
  - blog.html
  - contact.md

# Analytics (we'll add later)
google_analytics: 

# Comments (optional)
disqus:
  shortname:
